services:
  web:
    container_name: pomodoroWeb
    build:
      dockerfile: Dockerfile
    ports:
      - "5133:8080"
    depends_on:
      - postgres
      - mongodb

  postgres:
    container_name: postgres-db
    image: postgres:12.22-alpine3.21@sha256:7c8f4870583184ebadf7f17a6513620aac5f365a7938dc6a6911c1d5df2f481a
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "pomodoro"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mongodb:
    container_name: mongo-db
    image: mongo:7.0.16-jammy@sha256:52ea2c0512ea8ac1ee6bf558711efbeb0332e0a2504caac24ad743cc9509738b
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  # environment:
  #   ConnectionStrings__Postgres: "Host=postgres-db;Database=pomodoro;Username=postgres;Password=YourStrong!Passw0rd;"
  #   ConnectionStrings__MongoDb: "mongodb://mongo:YourStrong!Passw0rd@mongo-db:27017"
volumes:
  mssql-data:
